---
- name: "Install dependencies"
  hosts: management
  user: ec2-user
  gather_facts: false
  become: yes

- name: "Fetch kubectl config"
  hosts: management
  user: ec2-user
  gather_facts: false
  become: yes
  vars:
    AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
  pre_tasks:
    - name: Create a kubeconfig file for the cluster
      shell: "aws eks update-kubeconfig --region {{ AWS_DEFAULT_REGION }} --name {{ ENVIRONMENT_NAME }}-cluster"
